hydra:
  output_subdir: null
  run:
    dir: 'log'

labelList: 
  person: "wskwijinu"
  bicycle: ""
  car: "tapaqain"
  motorcycle: "ugtul"
  airplane: ""
  bus: "kina'matno'tok"
  train: "Puljain"
  truck: "ugtul"
  boat: "walipot"
  traffic light: "waso'deskawel"
  fire hydrant: "samkuano"
  stop sign: "naqa'si"
  parking meter: "parking meter"
  bench: "punko'pa'senkue"
  bird: "sisip"
  cat: "kajue’nuj"
  dog: "lmu'j"
  horse: "te'sipow"
  sheep: "ijklue'wj"
  cow: "wenjitia'm"
  elephant: "elepn"
  bear: "mui'n"
  zebra: "si'bla"
  giraffe: "piji’skipat"
  backpack: "monti"
  umbrella: "poqatikney"
  handbag: "unte'j"
  tie: "uqji'taqane'j"
  suitcase: "lskueykn"
  frisbee: ""
  skis: ""
  snowboard: ""
  sports ball: "Tu'aqn"
  kite: ""
  baseball bat: "alje’mamkewey"
  baseball glove: "piljaqan"
  skateboard: ""
  surfboard: ""
  tennis racket: ""
  bottle: "pu'tay"
  wine glass: "gups'ji'j"
  cup: "tamplin"
  fork: "Sapte'kney"
  knife: "samqa'lo"
  spoon: "emqwanji'j"
  bowl: "lapo'l"
  banana: "panana"
  apple: "wenju'su'n"
  sandwich: ""
  orange: "nikjawiknej"
  broccoli: "wisawipuneksit"
  carrot: ""
  hot dog: ""
  pizza: ""
  donut: ""
  cake: "" 
  chair: "kutputi"
  couch: ""
  potted plant: "lamakom"
  bed: "npo’qn"
  dining table: "pataluti"
  toilet: "ni'ja'noq"
  tv: ""
  laptop: ""
  mouse: "apukji'j"
  remote:  ""
  keyboard: ""
  cell phone: ""
  microwave: ""
  oven: ""
  toaster: ""
  sink: ""
  refrigerator: ""
  book: "wi’katikn"
  clock: "na'ku'sedawei"
  vase: "wasuego'q"
  scissors: "tmitqi’knn"
  teddy bear: "mui'ne'j"
  hair drier: ""
  toothbrush: ""
